### ISSUE TITLE
Discrepancy Between Readme and License File Regarding Licensing Terms

### ISSUE THREAD

**Issue by eliasws** [milliorn/nextjs-13-firebase-starter#70]
I've noticed a potential discrepancy in the project's licensing information. The Readme file mentions that this project is distributed under the MIT License. However, the License file specifies AGPLv3. These two licenses have significantly different terms, which can affect how users utilize and distribute this project.

Given the nature of this project as a starter template, I believe clarity on the licensing terms is essential to prevent any misunderstandings or potential legal issues. The MIT License offers more permissive terms, which might be more in line with a starter template's purpose. In contrast, AGPLv3 has strict copyleft provisions, especially for networked applications.

Could you kindly clarify which license the project is intended to be under and update the respective files to reflect that? This will provide clarity for all users and contributors moving forward.

**Comment by milliorn** [comment]
#71 will correct the typo in the README.  The GNU Affero General Public License is the correct license. Thank you for spotting that error.

**Comment by eliasws** [comment]
@eliasws Thanks for clarifying. But this also means this starter should not be used as starting points for commercial projects which don't want to open source their whole project?

**Comment by milliorn** [comment]
> @eliasws Thanks for clarifying. But this also means this starter should not be used as starting points for commercial projects which don't want to open source their whole project?

To be honest, I'm not sure, and I am not a lawyer. My main concern was someone for profit wanting to take this and make it close to source, and then try to take legal action in the future because of it.

**Comment by milliorn** [comment]
@eliasws has the issue been resolved?
